if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5eb6c816e823c',
	'title' => 'Blocks',
	'fields' => array(
		array(
			'key' => 'field_5eb6cc33ffcd4',
			'label' => 'Blocks',
			'name' => 'blocks',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_5eb6cdc3ffcd7' => array(
					'key' => 'layout_5eb6cdc3ffcd7',
					'name' => 'teasers',
					'label' => 'Teasers Block',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ed21275c50e7',
							'label' => 'Block Settings',
							'name' => 'block_settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5ed20992d2a5d',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5ed21650dc61d',
							'label' => 'Teaser Settings',
							'name' => 'teaser_settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5ed21568cdc2f',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5eb6cdf1ffcd8',
							'label' => 'Teasers',
							'name' => 'teasers',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5eb7716d34e78',
										'operator' => '==',
										'value' => 'wordpress',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'block',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5eb6cfe067ffb',
									'label' => 'Teaser',
									'name' => 'teaser',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5eb6cff267ffc',
											'label' => 'Kicker',
											'name' => 'kicker',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5eb770f334e77',
														'operator' => '!=',
														'value' => 'image_teasers',
													),
												),
											),
											'wrapper' => array(
												'width' => '25',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_5eb6cffc67ffd',
											'label' => 'Headline',
											'name' => 'headline',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5eb770f334e77',
														'operator' => '!=',
														'value' => 'image_teasers',
													),
												),
											),
											'wrapper' => array(
												'width' => '50',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_5eb6d02467fff',
											'label' => 'URL',
											'name' => 'url',
											'type' => 'link',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '25',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'array',
										),
										array(
											'key' => 'field_5eb6d00167ffe',
											'label' => 'Lead',
											'name' => 'lead',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5eb6cffc67ffd',
														'operator' => '!=empty',
													),
												),
												array(
													array(
														'field' => 'field_5eb770f334e77',
														'operator' => '!=',
														'value' => 'image_teasers',
													),
												),
											),
											'wrapper' => array(
												'width' => '75',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_5eb6d0a729469',
											'label' => 'Image',
											'name' => 'image',
											'type' => 'image',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '25',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'id',
											'preview_size' => 'crop-100x100',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => '',
											'mime_types' => '',
										),
									),
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5edb84e8bc1fc' => array(
					'key' => 'layout_5edb84e8bc1fc',
					'name' => 'icons',
					'label' => 'Icons',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5edb84e8bc1fd',
							'label' => 'Block Settings',
							'name' => 'block_settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5ed20992d2a5d',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5edb84e8bc1fe',
							'label' => 'Icon Settings',
							'name' => 'icon_settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5ed21568cdc2f',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5edb84e8bc1ff',
							'label' => 'Teasers',
							'name' => 'icons',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5eb6cc33ffcd4',
										'operator' => '!=empty',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'block',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5edb84e8bc200',
									'label' => 'Icon',
									'name' => 'icon',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5edb84e8bc201',
											'label' => 'Kicker',
											'name' => 'kicker',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5eb770f334e77',
														'operator' => '!=',
														'value' => 'image_teasers',
													),
												),
											),
											'wrapper' => array(
												'width' => '25',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_5edb84e8bc202',
											'label' => 'Headline',
											'name' => 'headline',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5eb770f334e77',
														'operator' => '!=',
														'value' => 'image_teasers',
													),
												),
											),
											'wrapper' => array(
												'width' => '50',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_5edb84e8bc203',
											'label' => 'URL',
											'name' => 'url',
											'type' => 'link',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '25',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'array',
										),
										array(
											'key' => 'field_5edb84e8bc204',
											'label' => 'Lead',
											'name' => 'lead',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5edb84e8bc202',
														'operator' => '!=empty',
														'value' => '',
													),
												),
												array(
													array(
														'field' => 'field_5eb770f334e77',
														'operator' => '!=',
														'value' => 'image_teasers',
													),
												),
											),
											'wrapper' => array(
												'width' => '75',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_5edb84e8bc205',
											'label' => 'Image',
											'name' => 'image',
											'type' => 'font-awesome',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '25',
												'class' => '',
												'id' => '',
											),
											'icon_sets' => array(
												0 => 'fas',
												1 => 'far',
												2 => 'fab',
											),
											'custom_icon_set' => '',
											'default_label' => '&lt;i class="fas"&gt;&lt;/i&gt; heart',
											'default_value' => 'fas fa-heart',
											'save_format' => 'element',
											'allow_null' => 0,
											'show_preview' => 1,
											'enqueue_fa' => 0,
											'fa_live_preview' => '',
											'choices' => array(
											),
										),
									),
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5eba89ac59535' => array(
					'key' => 'layout_5eba89ac59535',
					'name' => 'teasers_via_json',
					'label' => 'Teasers (Via JSON)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ed235c0ae259',
							'label' => 'Block Settings',
							'name' => 'block_settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5ed20992d2a5d',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5eba89ac59536',
							'label' => 'Teaser Settings',
							'name' => 'teaser_settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5ed21568cdc2f',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5ed23c7e4cfc2',
							'label' => 'JSON Settings',
							'name' => 'json_settings',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5eba89ac59537',
									'label' => 'JSON URL',
									'name' => 'json_url',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '75',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5eba89ac59538',
									'label' => 'Post Count',
									'name' => 'teaser_count',
									'type' => 'number',
									'instructions' => 'Number of results...',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5eb6cc33ffcd4',
												'operator' => '!=empty',
											),
										),
										array(
											array(
												'field' => 'field_5eb6cc33ffcd4',
												'operator' => '!=empty',
											),
										),
										array(
											array(
												'field' => 'field_5eb6cc33ffcd4',
												'operator' => '!=empty',
											),
										),
									),
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'default_value' => 6,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => 3,
									'max' => '',
									'step' => '',
								),
								array(
									'key' => 'field_5ed23604ae25a',
									'label' => 'JSON Value',
									'name' => 'json_value',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5eba89ac59537',
												'operator' => '!=empty',
												'value' => '',
											),
										),
									),
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5eba4b4263bb7' => array(
					'key' => 'layout_5eba4b4263bb7',
					'name' => 'teasers_via_category',
					'label' => 'Teasers (via category)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ed23589ae257',
							'label' => 'Block Settings',
							'name' => 'block_settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5ed20992d2a5d',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5eba4b4263bb9',
							'label' => 'Teaser Settings',
							'name' => 'teaser_settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5ed21568cdc2f',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5eba4b4263bc3',
							'label' => 'Category',
							'name' => 'category',
							'type' => 'taxonomy',
							'instructions' => 'Choose Category you want to get posts from.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'category',
							'field_type' => 'select',
							'allow_null' => 0,
							'add_term' => 0,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
						array(
							'key' => 'field_5eda5ffa9ae3c',
							'label' => 'Tag',
							'name' => 'tag',
							'type' => 'taxonomy',
							'instructions' => 'Choose Category you want to get posts from.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'post_tag',
							'field_type' => 'select',
							'allow_null' => 0,
							'add_term' => 0,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
						array(
							'key' => 'field_5eba4b4263bc4',
							'label' => 'Post Count',
							'name' => 'teaser_count',
							'type' => 'number',
							'instructions' => 'How many post teasers would you like pulled from the categories?',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5eb6cc33ffcd4',
										'operator' => '!=empty',
									),
								),
								array(
									array(
										'field' => 'field_5eb6cc33ffcd4',
										'operator' => '!=empty',
									),
								),
								array(
									array(
										'field' => 'field_5eb6cc33ffcd4',
										'operator' => '!=empty',
									),
								),
							),
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => 6,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 3,
							'max' => '',
							'step' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f10770469bb0' => array(
					'key' => 'layout_5f10770469bb0',
					'name' => 'layout_via_category',
					'label' => 'Layout (via Category)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f10770469bb3',
							'label' => 'Category',
							'name' => 'category',
							'type' => 'taxonomy',
							'instructions' => 'Choose Category you want to get posts from.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'category',
							'field_type' => 'select',
							'allow_null' => 0,
							'add_term' => 0,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
						array(
							'key' => 'field_5f10770469bb4',
							'label' => 'Tag',
							'name' => 'tag',
							'type' => 'taxonomy',
							'instructions' => 'Choose Category you want to get posts from.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'post_tag',
							'field_type' => 'select',
							'allow_null' => 0,
							'add_term' => 0,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5ed269455c44c' => array(
					'key' => 'layout_5ed269455c44c',
					'name' => 'text_block',
					'label' => 'Text Block',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ed269455c44d',
							'label' => 'Block Settings',
							'name' => 'block_settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5ed20992d2a5d',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5ed269685c456',
							'label' => 'Text Box',
							'name' => 'text_box',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5ed27e186954b' => array(
					'key' => 'layout_5ed27e186954b',
					'name' => 'split_block',
					'label' => 'Split Block',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ed27e186954c',
							'label' => 'Block Settings',
							'name' => 'block_settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5ed20992d2a5d',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5ed27e186954d',
							'label' => 'Teaser Settings',
							'name' => 'teaser_settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5ed21568cdc2f',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5ed27e186954f',
							'label' => 'Teaser',
							'name' => 'teaser',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5ed27e1869550',
									'label' => 'Kicker',
									'name' => 'kicker',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5eb770f334e77',
												'operator' => '!=',
												'value' => 'image_teasers',
											),
										),
									),
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5ed27e1869551',
									'label' => 'Headline',
									'name' => 'headline',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5eb770f334e77',
												'operator' => '!=',
												'value' => 'image_teasers',
											),
										),
									),
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5ed27e1869552',
									'label' => 'URL',
									'name' => 'url',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
								),
								array(
									'key' => 'field_5ed27e1869553',
									'label' => 'Lead',
									'name' => 'lead',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '75',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'basic',
									'media_upload' => 0,
									'delay' => 0,
								),
								array(
									'key' => 'field_5ed27e1869554',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '25',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'preview_size' => 'crop-100x100',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5ed3c784e60cd' => array(
					'key' => 'layout_5ed3c784e60cd',
					'name' => 'gallery_block',
					'label' => 'Gallery Block',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ed3c784e60ce',
							'label' => 'Block Settings',
							'name' => 'block_settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5ed20992d2a5d',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5ed3c79ee60d6',
							'label' => 'Gallery',
							'name' => 'gallery',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'insert' => 'append',
							'library' => 'all',
							'min' => '',
							'max' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f1716691141c' => array(
					'key' => 'layout_5f1716691141c',
					'name' => 'showcase',
					'label' => 'Showcase',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5f1716691141d',
							'label' => 'Block Settings',
							'name' => 'block_settings',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5ed20992d2a5d',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5f1726cf68006',
							'label' => 'Showcase Heading',
							'name' => 'showcase_heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Not required',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f1716691141f',
							'label' => 'Category',
							'name' => 'category',
							'type' => 'taxonomy',
							'instructions' => 'Choose Category you want to get posts from.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'category',
							'field_type' => 'select',
							'allow_null' => 1,
							'add_term' => 0,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
						array(
							'key' => 'field_5f17166911420',
							'label' => 'Tag',
							'name' => 'tag',
							'type' => 'taxonomy',
							'instructions' => 'Choose Category you want to get posts from.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'post_tag',
							'field_type' => 'select',
							'allow_null' => 0,
							'add_term' => 0,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
						array(
							'key' => 'field_5f17168711422',
							'label' => 'Layout',
							'name' => 'layout',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'showcase_5' => 'Default (Latest 5 posts)',
								'showcase_all' => 'Showcase all posts',
								'showcase_limit' => 'Showcase (set limit)',
							),
							'default_value' => false,
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5f171ecdc582a',
							'label' => 'Showcase Limit',
							'name' => 'showcase_limit',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f17168711422',
										'operator' => '==',
										'value' => 'showcase_limit',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 8,
							'max' => '',
							'step' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Item',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'shop',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;